Transfer course description
icssc/peterportal-client pull request #257
Opened 2023-02-12 05:07 UTC by MFYLM

## Description

Added text on transfer credits tab to allow users aware of naming requirements for matching transferable courses. Also thinking about include a list of missing courses on transfer credits tab to make it easier to type required class names.

## Screenshots

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/77956676/218294011-85e1e16f-4719-4206-acab-1c5698cd10c3.png">

## Steps to verify/test this change:

Go to roadmap and click transfer credits button on the top to view changes

## Final Checks:
- [ ] Verify successful deployment
- [ ] Delete branch

(optional)
- [ ] Write tests
- [ ] Write documentation

2023-02-27 23:16 UTC, ethanwong16 reviewed
Great work @MFYLM 🥳 !

Could you please remove the `.DS_Store` files and `package-lock.json` files from this PR?

The `.DS_Store` files are used for MacOS directories and should not be included in the repository (not sure why they were already there from before).  
We also didn't change any of the dependencies in this PR so `package-lock.json` should not be included either.

Once you address these quick changes please re-request a review from me, thanks!

2023-02-27 23:19 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/Header.tsx
> +  missingCourses: Set<string>;
Can you rename this variable to `missingPrerequisites`?

2023-02-27 23:20 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/Planner.tsx
> +              // console.log('missing', course.prerequisite_text);
Great for debugging but I think you can go ahead and delete this if you're not using it

2023-02-27 23:21 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/Planner.tsx
> +  const [missingCourses, setMissingCourses] = useState(new Set<string>);
Also please use `missingPrerequisites` here instead, just for some extra clarity

2023-02-27 23:23 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/Transfer.tsx
> +const Transfer: FC<MissingCoursesProps> = ({ names }) => {
Instead of names can you use something like `missingPrereqNames` ?

2023-02-27 23:25 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/Transfer.tsx
> +                <p>Notice: you need to include course names that match on UCI catalog (eg. "AP computer science" to "AP COMP SCI A")</p>
Can you update this description to say 

> Notice: entered course names need to match exactly as displayed on the UCI catalog (eg. "AP computer science" must be entered as "AP COMP SCI A")

2023-02-27 23:26 UTC, ethanwong16 commented
It looks like this PR is a duplicate of #257.  Could you close that PR and move the comments over here @MFYLM ?

2023-02-27 23:28 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/Header.tsx
> +      <Transfer names={missingCourses} />
Would be better to rename `names` to `missingPrereqNames`

2023-02-27 23:29 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/Transfer.tsx
> +interface MissingCoursesProps {
Would be good to rename this to `MissingPrereqProps`

2023-03-06 23:53 UTC, ryanmohta requested changes
I think it’s really cool how in addition to adding the description text, you added all the names of the missing prerequisites so the user knows exactly how to type them out! A couple of suggestions to make the feature more intuitive:
- Right now the list of missing prerequisites is just there by itself, and it’s not immediately obvious to the user what they represent; so having a small title right above the list with something like “Missing Prerequisites” would make the feature much easier to understand.
- I think a nice next step would be to have the names of the prereqs [be clickable](https://react-bootstrap.github.io/components/list-group/#actionable-items), and when you click on one of them it automatically adds it to the list of prereqs that the user has satisfied. We can probably save that for a future PR though

I see you’ve deleted the `.DS_Store` files, which is fine, but we want to make sure we don’t modify the `package.json` or `package-lock.json` files since we didn’t change any dependencies. Make sure you restore these files to how they were before you started making any changes, and once you do that feel free to re-request a review!

2023-03-14 02:46 UTC, ethanwong16 requested changes
@MFYLM great work on the updates!  There are still some unresolved conversations [here](https://github.com/icssc/peterportal-client/pull/257) and changes that Ryan requested, could you please go through them when you get a chance!  

When you address a conversation, make sure to mark it as resolved so it doesn't block your PR merging later.

Thanks 🔥

2023-03-15 02:09 UTC, ethanwong16 commented
Resolves #231  and #257

2023-04-21 22:24 UTC, ethanwong16 requested changes
Great job addressing the changes @MFYLM !
There a couple of minor suggestions, but could you please double check that nothing is changed on the `package-lock.json` and `package.json` files?

2023-04-21 22:24 UTC, ethanwong16 commented on package.json
Are these `package.json` and `package-lock.json` files being deleted from the branch? Or just from your PR?  The package files should not have any changes here ideally

2023-04-21 22:24 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/Transfer.tsx
> +                <p>Notice: you need to include course names that match on UCI catalog (eg. "AP computer science" to "AP COMP SCI A")</p>
Can you update this description to say 

> Notice: entered course names need to match exactly as displayed on the UCI catalog (eg. "AP computer science" must be entered as "AP COMP SCI A")

2023-05-05 07:13 UTC, ethanwong16 commented
@MFYLM to resolve the unintentional modification of package.json and package-lock.json files

1) please merge master branch into your current branch (to be up to date)
2) there should be merge conflicts, please **accept the master branch changes** and **ignore your branch's changes**
3) this will result in those files being fully synced with the master branch

2023-05-12 22:21 UTC, ethanwong16 approved these changes
Thanks for the hardworking @MFYLM ! Good work!

2023-05-16 03:49 UTC, merged