add year popup goes away when clicking outside
icssc/peterportal-client pull request #280
Opened 2023-03-19 19:52 UTC by AyushSat

This PR will allow the add year popup to be closed when anywhere else on the page is clicked.

Added event listeners to document to check where the clicks occur, if they are in the button toggle, else turn off the popup

Go to roadmap, press the add year to see popup, click outside the popup/button and see if it goes away.

2023-05-28 08:36 UTC, js0mmer requested changes
Looks good. One minor gripe I have is that the effect seems to go off and add/remove the event listener every time the popup is toggled since show is in the dependency array. I know it will show a warning when it's not in the dependency but there's another workaround using a function as it mentions in the error message. This will fix the adding/removing the listener on every toggle.

![image](https://github.com/icssc/peterportal-client/assets/8922227/5ba5e656-4ce6-490d-bdbd-ddc5dabc4819)

I left a suggestion with this change.

Also what does the popupTarget ref do? I see that it references the div you added but I don't see it used anywhere except the dependency array. Is this intentional?

2023-05-28 08:36 UTC, js0mmer commented on site/src/pages/RoadmapPage/AddYearPopup.tsx
> +  }, [popupTarget, target, show]);
```suggestion
  useEffect(() => {
    const handleClick = (event: MouseEvent) => {
      if (target.current && target.current.contains(event.target as Node)) {
        setShow(show => !show);
      } else {
        setShow(false);
      }
    };
    const rootElement = document.getElementById("root");
    if(rootElement){
      rootElement.addEventListener('click', handleClick);
    }
    return () => {
      if(rootElement){
        rootElement.removeEventListener('click', handleClick);
      }
    };
  }, [popupTarget, target]);
```

2023-06-09 22:02 UTC, ethanwong16 approved these changes
LGTM!  Take a quick look at my suggestion + Jacob's feedback 🔥

2023-06-09 22:02 UTC, ethanwong16 commented on site/src/pages/RoadmapPage/AddYearPopup.tsx
> +  useEffect(() => {
I'd suggest adding a quick comment here explaining the gist of the change and what it's purpose is, so it's easier to maintain or apply to other areas in the future

2023-12-07 04:40 UTC, js0mmer commented
Proper way of doing this would actually be to [use an OverlayTrigger](https://www.pluralsight.com/guides/how-to-dismiss-react-bootstrap-popover-on-click-outside)

2024-01-18 03:34 UTC, js0mmer commented
Will be redone using an [OverlayTrigger](https://react-bootstrap-v4.netlify.app/components/overlays/#overlay-trigger).

2024-01-18 03:34 UTC, closed without merging