Multiple plans
icssc/peterportal-client pull request #287
Opened 2023-04-27 21:45 UTC by MFYLM

## Description

- added multiplanner component 
- updated roadMapSlice to support multiple plans

## Screenshots
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/77956676/234997745-a7beba95-748c-470d-9fbe-6f87ee6ac855.png">

## Steps to verify/test this change:
- [ ] Verify changes work as expected on staging instance

## Final Checks:
- [ ] Verify successful deployment
- [ ] Delete branch

(optional)
- [ ] Write tests
- [ ] Write documentation

2023-05-05 07:17 UTC, ethanwong16 commented
Blocker for issue #194 , @SenghoungLim to update once closed

2023-05-05 21:24 UTC, SenghoungLim requested changes
Great job on this, it looks good. I have a few suggestions. 
1. I think once a user clicks on "Delete Plan", there should not be a scroll bar in the modal window. It might be confusing since we do not have more info to scroll down besides the cancel and delete buttons. 
<img width="471" alt="Delete Plan" src="https://user-images.githubusercontent.com/69941456/236569266-bb3792e0-68f4-4b80-8c98-05681e4dce21.png">

2. Ties from the first suggestion, once a user adds plan name, there should not be a scroll, I think it's inconvenient to scroll down to submit the plan. 
<img width="448" alt="image" src="https://user-images.githubusercontent.com/69941456/236569665-004c7ff9-69d4-4a0b-aa2c-fcd6a154ed9b.png">
3. It might be a nitpicking for me, but I think the sentence "Are you sure about deleting the current plan?" should change to "Are you sure you want to delete _"plan name"_? (You cannot undo this action)". I think this will allow users to know that it is permanent and ensure that they don't delete the wrong plan. It also shows consistency with other projects like AntAlmanac.

2023-06-09 23:48 UTC, ethanwong16 requested changes
LGTM!  

I'm just requesting more changes so if you could remove the `package-lock.json` and `package.json` issues and test it out on the staging instance before merging that would be great!

2023-10-19 07:22 UTC, js0mmer commented
Updated from main and handled merge conflicts. Should now have staging instance, be node 18 compatible, etc.

2023-10-27 19:19 UTC, js0mmer requested changes
Great start. A few things to note:
* Additional schedules are not saved locally or to your account if logged in when clicking save
  * upon reloading the page, additional schedules are lost
  * only the first schedule is saved, also the name of it is reset back to "Schedule 1"
* I would prefer that you used Bootstrap for the schedule selector, delete button, and modals
  * I think it makes more sense to stay consistent with the rest of the site and use Bootstrap rather than add MUI and have extra dependencies/different styling just for this feature
  * Also, I'm not too sure what the emotion package is but I don't think we need to add that either
* I would look into changing the UI for managing different schedules to be more like AntAlmanac's new schedule selector, with the edit button, delete, and add all in the same place
  * I think their new UI is more intuitive to use and we should copy that
![image](https://github.com/icssc/peterportal-client/assets/8922227/ce6fc64d-a980-432b-85c1-4459a9bb802a)
* Lastly, consider adding a "Cancel" button to the edit name/add schedule modals

2023-10-27 19:19 UTC, js0mmer commented on site/src/store/slices/roadmapSlice.ts
> +// export const { setRoadmapPlan, addRoadmapPlan, deleteRoadmapPlan } = roadmapMultiplePlanSlice.actions;
```suggestion
```

Remove if not needed.

2023-10-27 19:19 UTC, js0mmer commented on site/src/pages/RoadmapPage/RoadmapMultiplan.tsx
> +                            // console.log("selected index", newIndex);
```suggestion
```

2023-12-16 22:43 UTC, Awesome-E commented
> I would look into changing the UI for managing different schedules to be more like AntAlmanac's new schedule selector, with the edit button, delete, and add all in the same place
I think their new UI is more intuitive to use and we should copy that

I agree with this; maybe we could put it where it currently says "Peter's Roadmap"?
I'm thinking something like this:
<img width="739" alt="image" src="https://github.com/icssc/peterportal-client/assets/54484616/83b3cb13-5a63-4f69-aaa4-3aa34d86e4dc">

2024-05-08 19:38 UTC, Awesome-E commented
Progressed picked up in #472

2024-05-08 19:38 UTC, closed without merging