Implement Search Pagination
icssc/peterportal-client pull request #297
Opened 2023-05-12 11:04 UTC by aahei

Implement Search Pagination

## Description

- Create a `SearchPagination` component
- Remove the search result limit on WebSoc fuzzy search (may lower the performance)
In addition:
- Create `stc/helpers/constants.ts` to store `PAGE_SIZE`
- Add the "No results found" prompt.

The current config is:
- fetch all results at a time
- display 10 records on a page

## Screenshots

![image](https://github.com/icssc/peterportal-client/assets/18681247/66feb1de-60ef-43a8-8bfa-c608b0abd77a)

## Final Checks:
- [ ] Verify successful deployment
- [ ] Delete branch

(optional)
- [ ] Write tests
- [ ] Write documentation

2023-05-31 07:52 UTC, js0mmer approved these changes
LGTM! Great work 🔥

2023-05-31 07:54 UTC, js0mmer commented
Also, I'm guessing the issue you opened for performance improvements is meant for a new task/PR. I'm going to go ahead and unlink it from this PR so it doesn't close when this one merges.

2023-06-03 04:30 UTC, aahei commented
Just an inaccurate test: 
Before improvement, it takes around 4000-5000 ms to load the course results with an empty query (~5900 results).
After improvement, it takes 2000-3000 ms.

2023-06-09 22:49 UTC, aahei commented
Improvement: load only the first 5 pages initially, but when the user jumps to the 3rd page or after, load all pages.

2023-06-09 22:53 UTC, aahei commented
Peterportal

> Improvement: load only the first 5 pages initially, but when the user jumps to the 3rd page or after, load all pages.

This is a temporary solution. Currently, PPAPI does not support range search, see https://github.com/icssc/peterportal-client/issues/310. We will change it to the actual range search upon the PPAPI update release.

2023-06-09 23:47 UTC, ethanwong16 requested changes
LGTM!  Just requested some minor changes :)) thanks!

2023-06-09 23:47 UTC, ethanwong16 commented on site/src/component/SearchPagination/SearchPagination.tsx
> +const SearchPagination: FC<SearchPaginationProps> = ({ index }) => {
Can you add some quick comments on this module explaining what it does and what some of the key functions do?

2023-06-09 23:47 UTC, ethanwong16 commented on site/src/helpers/constants.ts
> +export const PAGE_SIZE = 10;
I would suggest renaming this to something like `NUM_RESULTS_PER_PAGE` , but I'll leave this up to you :)

2023-10-21 00:33 UTC, aahei commented
Next todo: merge to Master

2023-11-30 06:20 UTC, aahei commented
Next todo: test, also test #366

2024-02-01 06:20 UTC, js0mmer reviewed
Optimization seems to have broken for going past page 3. Gets stuck in an infinite loop. Dark mode theming needed for pagination component.

2024-02-01 08:29 UTC, aahei commented
> Optimization seems to have broken for going past page 3. Gets stuck in an infinite loop. Dark mode theming needed for pagination component.

Thank you for noting this. It didn't happen when I tested it, so it might be some side effect when merging with the new code since this functionality was written a long time ago. I will try to investigate this on this weekend.

2024-02-11 23:18 UTC, js0mmer commented
> > Optimization seems to have broken for going past page 3. Gets stuck in an infinite loop. Dark mode theming needed for pagination component.
> 
> Thank you for noting this. It didn't happen when I tested it, so it might be some side effect when merging with the new code since this functionality was written a long time ago. I will try to investigate this on this weekend.

Honestly, I think we can leave out the first 5 pages limiter. I've tested locally and performance seems to be fine with this current version of fuzzy search. I think we should also lower the search delay from 500ms to 300ms so response times are a bit faster.

2024-02-12 18:59 UTC, js0mmer commented
> > > Optimization seems to have broken for going past page 3. Gets stuck in an infinite loop. Dark mode theming needed for pagination component.
> > 
> > 
> > Thank you for noting this. It didn't happen when I tested it, so it might be some side effect when merging with the new code since this functionality was written a long time ago. I will try to investigate this on this weekend.
> 
> Honestly, I think we can leave out the first 5 pages limiter. I've tested locally and performance seems to be fine with this current version of fuzzy search. I think we should also lower the search delay from 500ms to 300ms so response times are a bit faster.

Nevermind, seems like it is necessary given that changing between catalogue/roadmap tabs slows down when searching the additional results.

2024-02-13 01:23 UTC, js0mmer commented
Found a solution: moving the states for `hasFullResults` and `lastQuery` into the redux slice seems to prevent these infinite loops. Will implement along with theming then this should be good to go.

2024-02-13 05:34 UTC, merged