Senghoung/edit review feature
icssc/peterportal-client pull request #426
Opened 2024-02-13 21:18 UTC by SenghoungLim

## Description
- Added edit review feature in user's review menu/tab.
- Added delete confirmation dialog for user's review.
- Added user-friendly design of the edit pen icon accommodating dark mode.

## Screenshots
- Showcase of delete review & pen UI for dark/light mode
![Showcase of delete review & pen UI for dark/light mode](https://recordit.co/wcKj8gEztY.gif)
- Showcase delete review confirmation & dark/light mode UI
![Showcase delete review confirmation & dark/light mode UI](https://recordit.co/2nV2MAziGq.gif)

## Steps to verify/test this change:
- [ ] Verify changes work as expected on staging instance

## Final Checks:
- [ ] Verify successful deployment

(optional)
- [ ] Write tests
- [ ] Write documentation

## Issues

Closes #273

2024-02-14 04:54 UTC, Awesome-E commented
Not going to review the whole PR since I'm not assigned to it, but I do have a few comments on design

I know what you have is the default style for the modal, but I think you should make it look more like the design and/or the one I made in #419. To be more specific, that is:

- Making the X bigger to match the size of the heading on the left
- not having the borders on bottom and top because that looks cleaner
- Modal background color should be one of the overlay colors (I forget which one, but it's in my PR)

---

Also, the edit button from your GIF appears to not be square, which makes the backdrop an oval instead of a circle. To be honest, I think don't think we should have it as a circle at all. Instead, I think we should keep the UI consistent with other parts of PPC and do the same thing like we do in the roadmap – that is, have a transparent button that is of the variant "light/dark depending on theme".

2024-02-14 05:44 UTC, js0mmer requested changes
Works well except for 2 things:
* reCAPTCHA has no effect, should implement or just omit it for review edits which I think may be safe to do, given that the resource already exists
* Form validation does not reset. If I edit a review then go to edit it again, green outlines and check marks are still there.
![image](https://github.com/icssc/peterportal-client/assets/8922227/57a79215-cc01-41e2-bfbc-a00c981ba69d)

Left additional comments, mainly on small refactors and design

2024-02-14 05:44 UTC, js0mmer commented on package.json
> +    "react-icons": "^5.0.1",
Would prefer not to add another icon pack/dependency just for one icon. We already have react bootstrap icons, let's use [one of their icons.](https://icons.getbootstrap.com/?q=pen)

2024-02-14 05:44 UTC, js0mmer commented on site/src/component/Review/SubReview.tsx
> +        </div>
Should make this a button not a div for accessibility purposes and then style it appropriately. I agree with Ethan's comments on the button styling.

2024-02-14 05:44 UTC, js0mmer commented on site/src/component/ReviewForm/ReviewForm.tsx
> +  }, [showForm]);
Add the dependencies to clear the warning. The lint check will allow warnings but our goal should be to have none so let's make sure not to add anymore.

```suggestion
  }, [showForm, cookies.user, props]);
```

2024-02-14 05:44 UTC, js0mmer commented on site/src/component/ReviewForm/ReviewForm.tsx
> +    if (props.editable === false) {
```suggestion
    if (!props.editable) {
```

2024-02-14 05:44 UTC, js0mmer commented on site/src/component/UserReviews/UserReviews.tsx
> +    });
```suggestion
```

2024-02-14 05:44 UTC, js0mmer commented on site/src/component/UserReviews/UserReviews.tsx
> +    console.log('Edit Review clicked!');
```suggestion
```

2024-02-14 05:44 UTC, js0mmer commented on site/src/component/UserReviews/UserReviews.tsx
> +                    </Button>
I would say cancel instead.

```suggestion
                    <Button variant="secondary" onClick={handleClose}>
                      Cancel
                    </Button>
```

2024-10-10 06:08 UTC, js0mmer commented
replaced by #487

2024-10-10 06:08 UTC, closed without merging