Prerequisite unmet  popup in search results
icssc/peterportal-client pull request #458
Opened 2024-03-06 22:24 UTC by timobraz

## Description
When searching for a course, an indicator may show up in the search bar if you haven't met prerequisites from your current roadmap.

## Screenshots

https://github.com/icssc/peterportal-client/assets/35554964/fc16ea05-c53d-4c2f-bad3-ea08e39f2a13

## Steps to verify/test this change:

- [ ] Verify changes work as expected on staging instance

## Final Checks:

- [ ] Verify successful deployment

(optional)

- [ ] Write tests
- [ ] Write documentation

## Issues

Closes #451

2024-03-07 01:21 UTC, Awesome-E commented
I think the icon itself is not very easy to tell what it means. Why not just make it consistent with what happens if you actually put it on the roadmap, that is, use the warning sign icon (at least for now)?

2024-03-07 21:53 UTC, js0mmer reviewed
I think the warning icon should be moved to the bottom left so it is consistent with the roadmap. Additionally, top right would conflict with #462.
Why not reuse the existing warning popover/logic?

2024-03-13 01:38 UTC, timobraz commented
> I think the warning icon should be moved to the bottom left so it is consistent with the roadmap. Additionally, top right would conflict with #462. Why not reuse the existing warning popover/logic?

The current popover logic relies on finding invalid courses that are **already** in the roadmap by going through each course and creating an array of objects that have `location` and `required` fields.  

This will probably have to be refactored in a PR of a different scope because the current way the roadmap detects unmatched prerequisites isn't reusable to `SearchHitItem`.

2024-04-19 05:36 UTC, js0mmer reviewed
Looks good. My one concern though is that the logic for this is implemented in SearchHitContainer component which is also reused for the course/professor catalog pages. It doesn't seem to be cause any errors though.

2024-05-11 18:37 UTC, js0mmer requested changes

2024-05-11 18:37 UTC, js0mmer commented on site/src/component/SearchHitContainer/SearchHitContainer.tsx
> +  );
Needs a fix for the multiplanner.

```suggestion
  const allExistingCourses = roadmap?.plans[roadmap.currentPlanIndex].content.yearPlans.flatMap((yearPlan) =>
    yearPlan.quarters.flatMap((quarter) => quarter.courses),
  );
```

2024-10-16 19:11 UTC, js0mmer approved these changes

2024-10-16 19:11 UTC, merged