added button to duplicate roadmap
icssc/peterportal-client pull request #532
Opened 2024-12-07 03:01 UTC by timobraz

New button to duplicate currently selected roadmap.
Will copy the content of the selected roadmap and select the copy upon duplication.
## Description

## Screenshots
![image](https://github.com/user-attachments/assets/bc923706-2a12-46b7-9a48-77a0973dd0df)

## Steps to verify/test this change:

- [ ] Verify changes work as expected on staging instance

## Final Checks:

- [ ] Verify successful deployment

(optional)

- [ ] Write tests
- [ ] Write documentation

## Issues

Closes #

2024-12-09 21:38 UTC, Awesome-E reviewed
Changes seem to work correctly, and code looks good! A couple things to note though:
- Transfers are separate from the roadmap so they're not really "copied" but rather it's just reading the same one. It does still work though
- I think it'd make more sense to have the duplicate button between the pencil and the trash can icons, because right now it's not clear (even with text) that "duplicate roadmap" refers to the current one (it may be confused as a button to open a selection menu). I don't know how technically difficult it would be to make it so that every roadmap can be duplicated easily, but I think it's worth exploring

2024-12-30 00:33 UTC, charlieweinberger reviewed
LGTM. However, I agree with Ethan's 2nd point, and think if possible it should be implemented before merging with main. See AntAlmanac as an example.

2025-01-06 23:43 UTC, timobraz commented
![image](https://github.com/user-attachments/assets/c06f15d9-e646-473f-9ae7-96f7daa277ed)
Addressed the changes to look more like Ant Almanac and be more explicit about which roadmap you're duplicating.

2025-01-08 01:59 UTC, Awesome-E requested changes

2025-01-08 01:59 UTC, Awesome-E commented on site/src/pages/RoadmapPage/RoadmapMultiplan.tsx
> -    }
Copying does not seem to increment the numbers correctly after this change. I assume it's because of this.
<img width="472" alt="image" src="https://github.com/user-attachments/assets/2b4b5080-1733-43a0-81bf-031046460214" />

2025-01-09 20:22 UTC, Awesome-E commented
Is it intended that duplicating "test (copy)" creates "test (copy) (copy)" instead of "test (copy 2)"?

2025-01-10 18:42 UTC, Awesome-E approved these changes

2025-01-11 21:07 UTC, merged