Update SubReview.tsx
icssc/peterportal-client pull request #534
Opened 2024-12-07 03:25 UTC by philosolog

## Description

## Screenshots

## Steps to verify/test this change:

- [ ] Verify changes work as expected on staging instance

## Final Checks:

- [ ] Verify successful deployment

(optional)

- [ ] Write tests
- [ ] Write documentation

## Issues

Closes #

2025-01-13 17:00 UTC, Awesome-E requested changes
When I go to edit a review, the review text gets updated immediately upon saving, but I have to reload the page before "Updated at [date]" appears

2025-01-13 22:38 UTC, Awesome-E commented
when you're ready for re-review, don't forget to click this button as well:
![image](https://github.com/user-attachments/assets/4950fdc5-67d6-4f49-a53a-e4a56c1e2844)

2025-01-16 07:50 UTC, charlieweinberger commented
Not sure exactly what the changes are here, but this seems like it'd conflict with my pull request #552, which heavily modifies SubReview.tsx. Just something to keep in mind, although this seems like a minor change that I could easily integrate into my pr.

2025-01-28 19:17 UTC, Awesome-E reviewed
It looks like because of the other changes on the review card, "posted" and "created" are now duplicates, and some other layout stuff happened.

I can take a look at this later

<img width="306" alt="image" src="https://github.com/user-attachments/assets/acc2d783-d923-4d2e-aea9-ca596488e969" />

2025-01-28 20:10 UTC, Awesome-E reviewed
Looks better now! Only issue is that when I create a new review, it automatically populates the "updated at" now

2025-01-29 00:11 UTC, Awesome-E approved these changes
Yay!

2025-01-29 09:01 UTC, timobraz approved these changes
Staged instance works as expected

2025-01-29 16:55 UTC, Awesome-E commented
I'll merge this one now, but in the future @philosolog you can merge if you get the approvals

2025-01-29 16:55 UTC, merged